{% set name = "ivmodels" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ivmodels-{{ version }}.tar.gz
  sha256: feaebe1acaa45dc6b7aba2532ce65b4ad15115b8272fbed06e09883c57574b4b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scikit-learn
    - glum
    - scipy
  run_constrained:
    - sphinx >=3.0.0,<4.0.0
    - sphinx-autodoc-typehints >=1.11.1,<2.0.0

test:
  imports:
    - ivmodels
    - ivmodels.models.kclass
    - ivmodels.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mlondschien/ivmodels
  summary: IV Models
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://ivmodels.readthedocs.io/
  dev_url: https://github.com/mlondschien/ivmodels

extra:
  recipe-maintainers:
    - mlondschien
